options-for-generic-webhook
fluxcd/notification-controller pull request #291
Opened 2021-11-23 17:12 UTC by boxcee

2021-11-23 20:40 UTC, yebyen commented
Hi @boxcee ! Thanks for your contribution here,

Can you please update the PR description with some explanation about what is added here? When you are ready to have it reviewed, can you please make sure the DCO bot is satisfied, and that you have squashed and/or `--sign-off`ed your commits?

2021-11-23 20:53 UTC, boxcee commented
@yebyen done 👍🏾

2021-12-13 10:30 UTC, modalkonform commented
@yebyen 
Is there any chance this change will get merged soon?

2022-01-10 09:02 UTC, stefanprodan requested changes

2022-01-10 09:02 UTC, stefanprodan commented on docs/spec/v1beta1/provider.md
> +data:
Please use `stringData` e.g.
```yaml
stringData:
  headers: |
     Authorization: token
     X-Forwarded-Proto: https
```

Also explain how the `headers` are used.

2022-01-11 13:34 UTC, kingdonb commented
Can you provide a bit more detail about the example of use for documentation? I understand the sample and the change, I'm just unsure about how the GitHub side of the configuration would look like, and how Flux users should discover this feature.

The example added in the doc isn't given any context or description in the current revision of the PR. That would make this finished, afaict 👍 @boxcee the branch has merge conflicts right now and so, looks like it must be rebased in order to merge.

2022-01-26 14:23 UTC, stefanprodan commented
Superseded by #317

2022-01-26 14:23 UTC, closed without merging

2022-02-12 11:38 UTC, alekspog commented
@boxcee hi, how do you trigger Github workflows with /dispatches URL with generic notification provider? It seems that Github repository_dispatch trigger requires a mandatory `type_event` field https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event, but I don't see how to pass custom fields with this generic provider.