Add GitLab notifier
fluxcd/notification-controller pull request #43
Opened 2020-09-13 19:21 UTC by phillebaba

Adds a notifier for GitLab that acts in a similar manner to the GitHub notifier.

Closes #40

**The front page of the repository**
![image](https://user-images.githubusercontent.com/10550243/93026543-f80c1700-f606-11ea-9840-fbf544fc50cd.png)

**Pipeline detailed view**
![image](https://user-images.githubusercontent.com/10550243/93026516-bbd8b680-f606-11ea-999f-db67b1ac7831.png)

**Info on mouse hover**
![image](https://user-images.githubusercontent.com/10550243/93026523-c7c47880-f606-11ea-9f04-6a5cc7d50af5.png)

2020-09-14 18:55 UTC, phillebaba commented
The latest commit should also close #44.

2020-09-15 18:04 UTC, phillebaba commented
Default value annotations was verified that it worked in kind 1.16.4

2020-09-19 10:26 UTC, stefanprodan requested changes

2020-09-19 10:26 UTC, stefanprodan commented on internal/notifier/discord.go
> +	if status, ok := event.Metadata["commit_status"]; ok && status == "update" {
Can we please make this into a function `IsCommitStatus` and reuse it in all providers.

2020-09-19 10:44 UTC, stefanprodan approved these changes
LGTM

Thanks @phillebaba 🎖️

2020-09-19 12:33 UTC, merged