Add GitHub App support
fluxcd/notification-controller pull request #437
Opened 2022-11-09 22:05 UTC by christopherL91

This PR adds support for using [Github Apps](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps).

A user is supposed to add `appID` `installationID` and `privateKey` as secret fields in order to use this new provider.

2022-11-09 22:16 UTC, christopherL91 commented
I will add some tests to test this new provider

2022-11-22 15:10 UTC, christopherL91 commented
@hiddeco Sorry to bother you but I haven't heard any feedback regarding this PR. Do you accept PRs from external parties?
I'm fully aware that I would need to add some tests but otherwise I don't see anything wrong with this implementation.

2022-11-22 16:01 UTC, makkes requested changes
Please add appropriate tests.

2022-11-29 05:45 UTC, christopherL91 commented on go.mod
> +	github.com/google/go-github/v45 v45.2.0 // indirect
Solved by depending on `github.com/google/go-github/45 v45.2.0`, updating the current `go-github` version

2022-11-29 08:34 UTC, christopherL91 commented
Hi @makkes! I've made some recent updates and I think most of the things you requested are now done. Please take a look :)

2022-12-01 10:07 UTC, makkes approved these changes

2022-12-01 10:44 UTC, makkes requested changes
Sorry, I missed the missing unit tests before. If that's added, this is good to go.

2022-12-01 10:44 UTC, makkes commented on internal/notifier/github.go
> +func NewGitHubApp(addr string, appID int64, installationID int64, privateKey []byte, certPool *x509.CertPool) (*GitHub, error) {
This func has 0 test coverage. Please add appropriate unit tests. The tests for `NewGitHub` might serve as an example.

2022-12-13 15:08 UTC, stefanprodan commented
@christopherL91 this need to be ported to the v1beta2 API, we've deprecated v1beta1 in the main branch and that version is now freezed.

2023-01-30 12:53 UTC, makkes commented
Summary of what's needed here to get the PR merged:

- rebase and port to v1beta2 API
- add unit test [as requested](https://github.com/fluxcd/notification-controller/pull/437#discussion_r1036956295)
- add documentation to [/docs/spec/v1beta2/providers.md](https://github.com/fluxcd/notification-controller/blob/main/docs/spec/v1beta2/providers.md)

2023-12-06 15:03 UTC, closed without merging