feat: add gitea notifier
fluxcd/notification-controller pull request #451
Opened 2022-12-04 02:50 UTC by ttys3

Gitea is a forge software package for hosting software development version control using Git as well as other collaborative features like bug tracking, code review, kanban boards, tickets, and wikis. It supports self-hosting but also provides a free public first-party instance

https://github.com/go-gitea/gitea

2022-12-04 08:11 UTC, makkes requested changes

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +import (
Please arrange the imports here the same way as in the other files of this package. https://github.com/golang/go/wiki/CodeReviewComments#imports

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +	debug   bool
These should be public as well.

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +func NewGitea(addr string, token string, certPool *x509.CertPool) (*Gitea, error) {
```suggestion
func NewGitea(addr, token string, certPool *x509.CertPool) (*Gitea, error) {
```

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +		return nil, errors.New("github token cannot be empty")
```suggestion
		return nil, errors.New("gitea token cannot be empty")
```

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +		debug:   debug,
```suggestion
	return &Gitea{
		BaseURL: host,
		Token:   token,
		Owner:   comp[0],
		Repo:    comp[1],
		client:  client,
		debug:   os.Getenv("NOTIFIER_GITEA_DEBUG") == "true",
```

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +	comp := strings.Split(id, "/")
```suggestion
	idComponents := strings.Split(id, "/")
```

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea.go
> +		return fmt.Errorf("could not list commit statuses: %v", err)
```suggestion
		return fmt.Errorf("could not list commit statuses: %w", err)
```

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea_test.go
> +Copyright 2020 The Flux authors
```suggestion
Copyright 2022 The Flux authors
```

2022-12-04 08:11 UTC, makkes commented on internal/notifier/gitea_test.go
> +/*
Please also test the `Post` method appropriately.

2022-12-04 11:41 UTC, ttys3 commented
the tests failed.  it complains about `config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml` which I added `gitea`

2022-12-07 14:35 UTC, kingdonb commented
I have an idea @ttys3 – it looks like you need to run `make generate` and commit the result. The error is a "dirty working tree" which just means that something in the e2e job runs `make generate` and you're supposed to already have run this.

I tried that locally but it only came up with half of the changes that failing test mentioned, the other one in `go.sum`

I guess that `make test` runs all of that

I found both the change in `go.sum` and in `notification[..]providers.yaml` like you mentioned. If you run the tests locally, you should get those changes in your working tree then you can commit them and e2e should hopefully pass after that 🎉

2022-12-08 13:43 UTC, ttys3 commented
@kingdonb `make test` will remove `gitea` from config/crd/bases/notification.toolkit.fluxcd.io_providers.yaml

`make generate` is right.

I need add `gitea` to api/v1beta1/provider_types.go, the yaml is generated from the annotation

2022-12-08 13:46 UTC, ttys3 commented
OK. fixed

PTAL

2022-12-08 14:01 UTC, makkes approved these changes

2022-12-08 14:01 UTC, makkes commented
@ttys3 please squash the commits into one.

2022-12-08 14:12 UTC, ttys3 commented
squash done.

2022-12-08 14:21 UTC, makkes approved these changes

2022-12-09 10:11 UTC, makkes submitted a review, later dismissed
@stefanprodan actually reminded me that we need to update the docs accordingly here. @ttys3 please add documentation about this new type to [the provider documentation page](https://github.com/fluxcd/notification-controller/blob/main/docs/spec/v1beta1/provider.md).

2022-12-09 15:25 UTC, ttys3 commented
@makkes added. PTAL

2022-12-13 15:08 UTC, stefanprodan commented
@ttys3 this need to be ported to the v1beta2 API, we've deprecated v1beta1 in the main branch and that version is now freezed.

2022-12-13 16:40 UTC, stefanprodan commented on api/v1beta1/provider_types.go
> +	// +kubebuilder:validation:Enum=slack;discord;msteams;rocket;generic;generic-hmac;github;gitlab;gitea;bitbucket;azuredevops;googlechat;webex;sentry;azureeventhub;telegram;lark;matrix;opsgenie;alertm
Please undo all the changes to v1beta1 and move them to v1beta2, then run codegen for the API docs.

2022-12-13 16:45 UTC, stefanprodan commented on docs/spec/v1beta1/provider.md
> +	// +kubebuilder:validation:Enum=slack;discord;msteams;rocket;generic;generic-hmac;github;gitlab;gitea;bitbucket;azuredevops;googlechat;webex;sentry;azureeventhub;telegram;lark;matrix;opsgenie;github
Please undo this change and add Gitea to the v1beta2 docs including a section about auth, like this https://github.com/fluxcd/notification-controller/blob/main/docs/spec/v1beta2/providers.md#github

2022-12-13 17:32 UTC, ttys3 commented
CI failed. force pushed.
PTAL

2022-12-14 08:16 UTC, stefanprodan approved these changes
LGTM 

Thanks @ttys3 🥇

2022-12-14 08:23 UTC, makkes approved these changes
Great job 🎖️

2022-12-14 08:23 UTC, merged